"use client";

import { useEffect, useState, use } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import type { AnalysisResult, Flag, ActionItem } from "@/types/analysis";
import type { Meeting } from "@/types/meeting";
import { formatDate, getSeverityColor } from "@/lib/utils";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default function ReportPage({ params }: PageProps) {
  const { id } = use(params);
  const [report, setReport] = useState<{
    meeting: Meeting;
    analysis: AnalysisResult;
    flags: Flag[];
    action_items: ActionItem[];
  } | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const data = await api.getReport(id);
        setReport(data as typeof report);
      } catch (err) {
        console.error(err);
      }
      setLoading(false);
    };
    load();
  }, [id]);

  const handleExport = async () => {
    const md = await api.exportReport(id);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report?.meeting?.title || "report"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading)
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-12 h-12 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin" />
      </div>
    );

  if (!report)
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-4xl mb-4">📋</p>
          <p className="text-[var(--text-secondary)]">Report not available yet.</p>
          <Link href="/dashboard" className="btn-primary mt-4 inline-block">Back to Dashboard</Link>
        </div>
      </div>
    );

  const { meeting, analysis, flags, action_items } = report;
  const vagueFlags = flags.filter((f) => f.flag_type === "vague");
  const contradictionFlags = flags.filter((f) => f.flag_type === "contradiction");

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <nav className="flex items-center justify-between px-8 py-4 border-b border-[var(--border-subtle)] print:hidden">
        <Link href="/dashboard" className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
            <span className="text-white font-bold text-sm">C</span>
          </div>
          <span className="text-lg font-bold">Clarity AI</span>
        </Link>
        <div className="flex gap-3">
          <Link href={`/meetings/${id}`} className="btn-secondary text-sm">← Analysis View</Link>
          <button onClick={handleExport} className="btn-primary text-sm">📥 Download .md</button>
          <button onClick={() => window.print()} className="btn-secondary text-sm">🖨 Print</button>
        </div>
      </nav>

      {/* Report Content */}
      <div className="max-w-4xl mx-auto px-8 py-12 animate-fade-in-up">
        {/* Header */}
        <div className="mb-10 pb-8 border-b border-[var(--border-subtle)]">
          <p className="text-sm text-[var(--accent-blue)] font-medium mb-2">MEETING INTELLIGENCE REPORT</p>
          <h1 className="text-4xl font-bold text-[var(--text-primary)] mb-3">{meeting.title}</h1>
          <p className="text-[var(--text-secondary)]">
            {formatDate(meeting.meeting_date || meeting.created_at)} · Generated by Clarity AI
          </p>
        </div>

        {/* Score Overview */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[
            { label: "Clarity Score", value: `${analysis.clarity_score}/100`, color: analysis.clarity_score >= 70 ? "text-emerald-400" : analysis.clarity_score >= 50 ? "text-amber-400" : "text-rose-400" },
            { label: "Commitment", value: `${analysis.commitment_score}/100`, color: "text-blue-400" },
            { label: "Contradictions", value: String(analysis.contradiction_count), color: analysis.contradiction_count > 0 ? "text-rose-400" : "text-emerald-400" },
            { label: "Action Items", value: String(action_items.length), color: "text-purple-400" },
          ].map((s) => (
            <div key={s.label} className="glass-card p-5 text-center">
              <div className={`text-2xl font-bold ${s.color}`}>{s.value}</div>
              <div className="text-xs text-[var(--text-muted)] mt-1">{s.label}</div>
            </div>
          ))}
        </div>

        {/* Summary */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">📝 Summary</h2>
          <div className="glass-card p-6">
            <p className="text-[var(--text-secondary)] leading-relaxed">
              {analysis.summary?.overview || "No summary available."}
            </p>
            {analysis.summary?.key_themes && analysis.summary.key_themes.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-4">
                {analysis.summary.key_themes.map((theme, i) => (
                  <span key={i} className="px-3 py-1 rounded-full text-xs bg-blue-500/15 text-blue-400 border border-blue-500/20">
                    {theme}
                  </span>
                ))}
              </div>
            )}
          </div>
        </section>

        {/* Decisions */}
        {analysis.decisions && analysis.decisions.length > 0 && (
          <section className="mb-10">
            <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">🎯 Key Decisions</h2>
            <div className="glass-card p-6">
              <ul className="space-y-3">
                {analysis.decisions.map((d, i) => (
                  <li key={i} className="flex items-start gap-3 text-[var(--text-secondary)]">
                    <span className="text-emerald-400 mt-0.5 flex-shrink-0">✓</span>
                    <span>{d}</span>
                  </li>
                ))}
              </ul>
            </div>
          </section>
        )}

        {/* Action Items */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">
            ✅ Action Items ({action_items.length})
          </h2>
          {action_items.length > 0 ? (
            <div className="glass-card p-6 overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-[var(--text-muted)] border-b border-[var(--border-subtle)]">
                    <th className="pb-3 pr-4">Description</th>
                    <th className="pb-3 pr-4">Owner</th>
                    <th className="pb-3 pr-4">Deadline</th>
                    <th className="pb-3">Priority</th>
                  </tr>
                </thead>
                <tbody>
                  {action_items.map((item) => (
                    <tr key={item.id} className="border-b border-[var(--border-subtle)] last:border-0">
                      <td className="py-3 pr-4 text-[var(--text-secondary)]">{item.description}</td>
                      <td className="py-3 pr-4">
                        <span className={item.owner === "Unassigned" ? "text-amber-400" : "text-[var(--text-primary)]"}>
                          {item.owner}
                        </span>
                      </td>
                      <td className="py-3 pr-4 text-[var(--text-muted)]">{item.deadline || "Not set"}</td>
                      <td className="py-3">
                        <span className={`px-2 py-0.5 rounded text-xs font-medium border ${getSeverityColor(item.priority)}`}>
                          {item.priority}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="glass-card p-6 text-center text-[var(--text-muted)]">No action items extracted.</div>
          )}
        </section>

        {/* Vague Statements */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">
            ⚠️ Vague Statements ({vagueFlags.length})
          </h2>
          {vagueFlags.length > 0 ? (
            <div className="space-y-3">
              {vagueFlags.map((f) => (
                <div key={f.id} className="glass-card p-5">
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`px-2 py-0.5 rounded text-xs font-medium border ${getSeverityColor(f.severity)}`}>
                      {f.severity}
                    </span>
                    {f.user_verdict && (
                      <span className="text-xs text-[var(--text-muted)]">
                        {f.user_verdict === "accepted" ? "✓ Accepted" : "✕ Rejected"}
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-[var(--text-secondary)]">{f.explanation}</p>
                </div>
              ))}
            </div>
          ) : (
            <div className="glass-card p-6 text-center text-emerald-400">No vague statements detected 🎉</div>
          )}
        </section>

        {/* Contradictions */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">
            🔴 Contradictions ({contradictionFlags.length})
          </h2>
          {contradictionFlags.length > 0 ? (
            <div className="space-y-3">
              {contradictionFlags.map((f) => (
                <div key={f.id} className="glass-card p-5 border-l-4 border-rose-500/50">
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`px-2 py-0.5 rounded text-xs font-medium border ${getSeverityColor(f.severity)}`}>
                      {f.severity}
                    </span>
                  </div>
                  <p className="text-sm text-[var(--text-secondary)]">{f.explanation}</p>
                </div>
              ))}
            </div>
          ) : (
            <div className="glass-card p-6 text-center text-emerald-400">No contradictions detected 🎉</div>
          )}
        </section>

        {/* Follow-ups */}
        {analysis.suggested_followups && analysis.suggested_followups.length > 0 && (
          <section className="mb-10">
            <h2 className="text-xl font-bold text-[var(--text-primary)] mb-4 flex items-center gap-2">📧 Suggested Follow-ups</h2>
            <div className="glass-card p-6">
              <ul className="space-y-3">
                {analysis.suggested_followups.map((f, i) => (
                  <li key={i} className="flex items-start gap-3 text-[var(--text-secondary)]">
                    <span className="text-blue-400 mt-0.5 flex-shrink-0">→</span>
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </div>
          </section>
        )}

        {/* Footer */}
        <div className="text-center text-xs text-[var(--text-muted)] pt-8 border-t border-[var(--border-subtle)]">
          Generated by Meeting Clarity AI · {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
